### ISSUE TITLE
Todas las funciones deben ser documentadas empleando JsDoc

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-bruna-abella#27]
Revisar la siguiente diapositiva y las 5 subsiguientes https://ucc-labcompu2.github.io/filminas/U5_javaScript1.html#/31

**Comment by edme88** [comment]
https://github.com/UCC-LabCompu2/proyecto2024-bruna-abella/blob/4ff6a6fdc2c8e766746eefc638fb7833d781eb86/main.js#L89

https://github.com/UCC-LabCompu2/proyecto2024-bruna-abella/blob/4ff6a6fdc2c8e766746eefc638fb7833d781eb86/main.js#L107

**Comment by Max20050** [comment]
Implementado en el siguiente push.
