### ISSUE TITLE
No emplear variables globales

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-bruna-abella#29]
Siempre es recomendable que las variables estén contenidas dentro de una función.
La única excepción en este proyecto es si una variable puntual se "complica" pasarla entre una función y otra.
Pero, en este caso, muchas variables podrían estar contenidas dentro de la función que realiza el dibujo en el canvas.
https://github.com/UCC-LabCompu2/proyecto2024-bruna-abella/blob/7719d8245a161b29953f8ea221582e3ead43a947/main.js#L1-L15

**Comment by Max20050** [comment]
Hola profe, las variables como : {imagen,pixelstep,scale,yscale...} fueron implementadas dentro de funciones pero la varible para el canvas quedo como global ya que es utilizada para varias funciones.
