### ISSUE TITLE
El event listener debería ser agregado del lado del HTML

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-bruna-abella#30]
https://github.com/UCC-LabCompu2/proyecto2024-bruna-abella/blob/7719d8245a161b29953f8ea221582e3ead43a947/main.js#L85

**Comment by Max20050** [comment]
`           <button class="button" type="reset"><a href="index.html" class="no-decoration">Reiniciar Gráfico</a>
                <script>document.addEventListener("submit",(form) => {generarGrafico(form);})</script>
            </button>
`
Profe, queria saber si se referia a esto. Y si quedaria bien implementado de esta forma.
