### ISSUE TITLE
Falta readme en el proyecto

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-bruna-abella#4]
El readme del proyecto debe contener mínimamente:

-  título del proyecto
- autores
- link de gh-pages
- contenido de la página
- listado de tecnologías usadas

En el readme.md se debe emplear [Markdown](https://ucc-labcompu2.github.io/filminas/U2_git_avanzado.html#/13) y aplicar negrita, titulo de orden 1, 2 y 3, link, items, tabla, index a cada sección

**Comment by Max20050** [comment]
Falta Agregar {contenido de la página y
listado de tecnologías usadas}
